[package]
name = "ripasso-gtk"
version = "0.3.0-alpha"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com>"]
edition = '2018'

[dependencies]
ripasso = { path = "../"}
gtk = { version = "0.5.0", features = ["v3_10"] }
glib = "0.6.0"
git2 = "0.10.2"
