[package]
name = "ripasso-gtk"
version = "0.5.0"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com>"]
edition = '2018'

[dependencies]
ripasso = { path = "../", version = "0.5.0" }
gtk = { version = "0.9.0", features = ["v3_22"] }
gdk = "0.13.0"
glib = "0.10.0"
lazy_static = "1.4.0"
clipboard = "0.5"
