[package]
name = "ripasso-qt"
version = "0.5.1"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com>"]
edition = '2018'

[dependencies]
clipboard = "0.5"
ripasso = { path = "../", version = "0.5.1" }
qml = { git = "https://github.com/White-Oak/qml-rust" }
