[package]
name = "ripasso-qt"
version = "0.3.0-alpha"
authors = ["Joakim Lundborg <joakim.lundborg@gmail.com>"]
edition = '2018'

[dependencies]
clipboard = "0.5"
ripasso = { path = "../"}
qml = { git = "https://github.com/White-Oak/qml-rust" }
git2 = "0.10.0"
